apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ jdk_imagestream_name }}
  namespace: {{ namespace_tools }}
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
    from:
      kind: DockerImage
      name: quay.io/emergencyresponsedemo/{{ jdk_imagestream_name }}:{{ jdk_imagestream_tag }}
    name: "{{ jdk_imagestream_tag }}"
