apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
    monitoring-key: "{{ application_monitoring_label_value }}"
  name: emergency-response-services-actuator
spec:
  endpoints:
    - interval: 5s
      path: /actuator/prometheus
      port: http
  selector:
    matchLabels:
      monitoring: prometheus-actuator
