# permissions for end users to edit erdemos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: erdemo-editor-role
rules:
- apiGroups:
  - apps.erdemo.io
  resources:
  - erdemos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.erdemo.io
  resources:
  - erdemos/status
  verbs:
  - get
